name: Deploy GitHub Pages

on:
  push:
    paths:
      - 'github_pages/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          sudo npm install -g n

      - name: Install dependencies
        run: |
          cd github_pages
          npm install

      - name: Set Git user for deploy
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Run deployment
        run: |
          cd github_pages
          CI=false npm run deploy
