name: Test workflow

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HUGGINGFACE_HUB_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project (dev deps)
        run: uv sync --group dev

      - name: Run tests
        run: bash test_git_workflow.sh
