name: Test workflow

on:
  push:

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Prepare submodules
        run: git submodule update --init --recursive

      - name: Install the project (dev deps)
        run: uv sync --group dev

      - name: Run tests (metrics)
        run: uv run pytest src/eval_mm/metrics/*.py

      - name: Run tests (tasks)
        run: uv run  pytest src/eval_mm/tasks/*.py

      # Optional model smoke; enable when runners have resources
      # - name: Run model smoke tests
      #   run: bash test_model.sh
